CC=gcc
CFLAGS=-Wall -Wextra
LIBS=-lpthread

exo1: exo1.c
	$(CC) $< -o $@ $(CFLAGS) $(LIBS)

exo1exec: exo1
	./$<

exo1semaphore: exo1
exo1semaphore: CFLAGS+=-DSEMAPHORE


exo2: exo2.c
	$(CC) $< -o $@ $(CFLAGS) $(LIBS)

exo2bis: exo2bis.c
	$(CC) $< -o $@ $(CFLAGS) $(LIBS)

exo3: exo3.c
	$(CC) $< -o $@ $(CFLAGS) $(LIBS)

clean:
	rm -f exo1 exo2 exo2bis exo3
